uri: containerops/component/python-component-pycco-build
title: Component for build python document with pycco
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-pycco-build
    title: Component, build python document with pycco
    sequencing: sequence
    actions:
      -
        name: pycco-build
        title: build your python document with pycco
        jobs:
          -
            type: component
            kubectl: pycco-build.yaml
            endpoint: hub.opshub.sh/containerops/pycco:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/pycco-docs/pycco.git"
      -
  -
    type: end
    name: end
    title: End
