apiVersion: v1
kind: Pod
metadata:
 name: pycco-build
spec:
 containers:
 - name: pycco
   image: hub.opshub.sh/containerops/pycco:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/pycco-docs/pycco.git"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never