appname = "component"
usage = "DevOps Workflow Engine "
version = "0.0.1"
author = "Meaglith Ma"
email = "genedna@gmail.com "

# include runtime.conf
runmode = "dev"

listenmode = "http"
projectaddr = "http://test-1.containerops.sh"
httpscertfile = "cert/containerops/containerops.sh.crt"
httpskeyfile = "cert/containerops/containerops.sh.key"

[log]
file = ""
level = "debug"
# is log print all request info,if set to true && level set to debug, all request info will be print
showReqInfo = false

[database]
driver = "mysql"
uri = "dev:dev@tcp(192.168.56.250:3306)/component?charset=utf8&parseTime=True&loc=Asia%2FShanghai"

[auth]
checker = ["strChecker", "tokenChecker"]
