uri: containerops/component/python-component-memory-profiler-test
title: Component for python profiling with memory_profiler
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-memory-profiler-test
    title: Component, python profiling with memory_profiler
    sequencing: sequence
    actions:
      -
        name: memory-profiler-test
        title: analysis your python memory usage
        jobs:
          -
            type: component
            kubectl: memory-profiler-test.yaml
            endpoint: hub.opshub.sh/containerops/memory_profiler:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/fabianp/memory_profiler.git entry-file=test/test_func.py"
      -
  -
    type: end
    name: end
    title: End
