uri: containerops/component/python-component-mkdocs-build
title: Component for build python document with mkdocs
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-mkdocs-build
    title: Component, build python document with mkdocs
    sequencing: sequence
    actions:
      -
        name: mkdocs-build
        title: build your python document with mkdocs
        jobs:
          -
            type: component
            kubectl: mkdocs-build.yaml
            endpoint: hub.opshub.sh/containerops/mkdocs:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/mkdocs/mkdocs.git entry-path=."
      -
  -
    type: end
    name: end
    title: End
