apiVersion: v1
kind: Pod
metadata:
 name: mkdocs-build
spec:
 containers:
 - name: mkdocs
   image: hub.opshub.sh/containerops/mkdocs:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/mkdocs/mkdocs.git entry-path=."
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never