uri: containerops/component/python-component-pycallgraph-test
title: Component for python call graph visualizations
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-pycallgraph-test
    title: Component, python call graph visualizations
    sequencing: sequence
    actions:
      -
        name: pycallgraph-test
        title: python call graph visualizations
        jobs:
          -
            type: component
            kubectl: pycallgraph-test.yaml
            endpoint: hub.opshub.sh/containerops/pycallgraph:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/bpnn.git entry-file=bpnn.py upload=https://hub.opshub.sh/binary/v1/containerops/component/binary/v0.1/pycallgraph"
      -
  -
    type: end
    name: end
    title: End
