uri: containerops/component/ctest/ci-component
title: CI build and test  for components
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: build-component
    title:  Component build and flow action
    sequencing: sequence
    actions:
      -
        name: build-component
        title: build-component-action
        jobs:
          -
            type: component
            kubectl:
            endpoint: hub.opshub.sh/containerops/component-ctest-build:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: ""
      -
        name: flow-component
        title: flow-component-action
        jobs:
          -
            type: component
            kubectl:
            endpoint: hub.opshub.sh/containerops/component-ctest-flow:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: ""
      -
  -
    type: end
    name: end
    title: End
