# Copyright 2016 - 2017 Huawei Technologies Co., Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

uri: cncf/demo-for-cncf-ci/build-test-release-deploy
title: Demo For Cloud Native Computing Foundation CI Working Group
version: 4
tag: latest
timeout: 0
receivers:
  -
    type: mail
    address: wangqilin@containerops.sh
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: servicecomb-bmi-checkstyle
    title: Building, testing bmi project.
    sequencing: sequence
    actions:
      -
        name: checkstyle-bmi
        title: Checktyle of bmi
        jobs:
          -
            type: component
            endpoint: wangkirin/analysis-java-gradle-checkstyle:latest
            resources:
              cpu: 1
              memory: 1G
            timeout: 0
            environments:
              - CO_DATA: "version=gradle3 git-url=https://github.com/wangkirin/bmi.git out-put-type=json report-path=./webapp/build/reports/checkstyle"
      -
        name: build-bmi
        title: Build bmi image by assembling
        jobs:
          -
            type: component
            endpoint: hub.opshub.sh/containerops/call-assembling:v0.83
            resources:
              cpu: 1
              memory: 1G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/wangkirin/bmi.git assembling-url=https://build.opshub.sh registry-url=hub.opshub.sh namespace=servicecomb image=bmitest tag=v0.3"
      -
        name: deploy-bmi
        title: Deploy bmi
        jobs:
          -
            type: component
            endpoint: wangkirin/create-deployment:latest
            resources:
              cpu: 1
              memory: 1G
            environments:
              - CO_DATA: "api-server-url=http://10.229.49.97:8080 base64-yaml-content=YXBpVmVyc2lvbjogZXh0ZW5zaW9ucy92MWJldGExCmtpbmQ6IERlcGxveW1lbnQKbWV0YWRhdGE6CiAgY3JlYXRpb25UaW1lc3RhbXA6IG51bGwKICBsYWJlbHM6CiAgICBpby5rb21wb3NlLnNlcnZpY2U6IGJtaS1jYWxjdWxhdG9yCiAgbmFtZTogYm1pLWNhbGN1bGF0b3IKc3BlYzoKICByZXBsaWNhczogMQogIHN0cmF0ZWd5OiB7fQogIHRlbXBsYXRlOgogICAgbWV0YWRhdGE6CiAgICAgIGNyZWF0aW9uVGltZXN0YW1wOiBudWxsCiAgICAgIGxhYmVsczoKICAgICAgICBpby5rb21wb3NlLnNlcnZpY2U6IGJtaS1jYWxjdWxhdG9yCiAgICBzcGVjOgogICAgICBjb250YWluZXJzOgogICAgICAtIGVudjoKICAgICAgICAtIG5hbWU6IEpBVkFfT1BUUwogICAgICAgICAgdmFsdWU6IC1EY3NlLnNlcnZpY2UucmVnaXN0cnkuYWRkcmVzcz1odHRwOi8vc2Muc2VydmljZWNvbWIuaW86MzAxMDAKICAgICAgICAtIG5hbWU6IEpBUl9OQU1FCiAgICAgICAgICB2YWx1ZTogY2FsY3VsYXRvci0wLjQuMC1TTkFQU0hPVAogICAgICAgIGltYWdlOiBodWIub3BzaHViLnNoL3NlcnZpY2Vjb21iL2JtaXRlc3Q6djAuMwogICAgICAgIG5hbWU6IGJtaS1jYWxjdWxhdG9yCiMgICAgICAgIHBvcnRzOgojICAgICAgICAtIGNvbnRhaW5lclBvcnQ6IDg4ODgKICAgICAgICByZXNvdXJjZXM6CiAgICAgICAgICByZXF1ZXN0czoKICAgICAgICAgICAgY3B1OiAyMDBtCiAgICAgIHJlc3RhcnRQb2xpY3k6IEFsd2F5cwo="

          -
            type: component
            endpoint: wangkirin/create-deployment:latest
            resources:
              cpu: 1
              memory: 1G
            environments:
              - CO_DATA: "api-server-url=http://10.229.49.97:8080 base64-yaml-content=YXBpVmVyc2lvbjogZXh0ZW5zaW9ucy92MWJldGExCmtpbmQ6IERlcGxveW1lbnQKbWV0YWRhdGE6CiAgY3JlYXRpb25UaW1lc3RhbXA6IG51bGwKICBsYWJlbHM6CiAgICBpby5rb21wb3NlLnNlcnZpY2U6IGJtaS13ZWJhcHAKICBuYW1lOiBibWktd2ViYXBwCnNwZWM6CiAgcmVwbGljYXM6IDEKICBzdHJhdGVneToge30KICB0ZW1wbGF0ZToKICAgIG1ldGFkYXRhOgogICAgICBjcmVhdGlvblRpbWVzdGFtcDogbnVsbAogICAgICBsYWJlbHM6CiAgICAgICAgaW8ua29tcG9zZS5zZXJ2aWNlOiBibWktd2ViYXBwCiAgICBzcGVjOgogICAgICBjb250YWluZXJzOgogICAgICAtIGVudjoKICAgICAgICAtIG5hbWU6IEpBVkFfT1BUUwogICAgICAgICAgdmFsdWU6IC1EY3NlLnNlcnZpY2UucmVnaXN0cnkuYWRkcmVzcz1odHRwOi8vc2Muc2VydmljZWNvbWIuaW86MzAxMDAKICAgICAgICAtIG5hbWU6IEpBUl9OQU1FCiAgICAgICAgICB2YWx1ZTogd2ViYXBwLTAuNC4wLVNOQVBTSE9UCiAgICAgICAgaW1hZ2U6IGh1Yi5vcHNodWIuc2gvc2VydmljZWNvbWIvYm1pdGVzdDp2MC4zCiAgICAgICAgbmFtZTogYm1pLXdlYmFwcAogICAgICAgIHBvcnRzOgogICAgICAgIC0gY29udGFpbmVyUG9ydDogODg4OAogICAgICAgIHJlc291cmNlczoKICAgICAgICAgIHJlcXVlc3RzOgogICAgICAgICAgICBjcHU6IDIwMG0KICAgICAgcmVzdGFydFBvbGljeTogQWx3YXlzCg=="

          -
            type: component
            endpoint: wangkirin/create-service:latest
            resources:
              cpu: 1
              memory: 1G
            environments:
              - CO_DATA: "api-server-url=http://10.229.49.97:8080 base64-yaml-content=YXBpVmVyc2lvbjogdjEKa2luZDogU2VydmljZQptZXRhZGF0YToKICBjcmVhdGlvblRpbWVzdGFtcDogbnVsbAogIGxhYmVsczoKICAgIGlvLmtvbXBvc2Uuc2VydmljZTogYm1pLXdlYmFwcAogIG5hbWU6IGJtaS13ZWJhcHAKc3BlYzoKICBwb3J0czoKICAtIG5hbWU6ICI4ODg4IgogICAgcG9ydDogODg4OAogICAgdGFyZ2V0UG9ydDogODg4OAogICAgbm9kZVBvcnQ6IDg5OTkKICAgIHByb3RvY29sOiBUQ1AKICB0eXBlOiBOb2RlUG9ydAogIHNlbGVjdG9yOgogICAgaW8ua29tcG9zZS5zZXJ2aWNlOiBibWktd2ViYXBwCg=="
  -
        name: release-bmi
        title: Release bmi image by assembling
        jobs:
          -
            type: component
            endpoint: hub.opshub.sh/containerops/call-assembling:v0.83
            resources:
              cpu: 1
              memory: 1G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/wangkirin/bmi.git assembling-url=https://build.opshub.sh registry-url=hub.opshub.sh namespace=servicecomb image=bmitest tag=v0.3"
  -
    type: end
    name: end
    title: End
    