uri: containerops/component/python-component-pdoc-build
title: Component for build python package document with pdoc
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-pdoc-build
    title: Component, build python package document with pdoc
    sequencing: sequence
    actions:
      -
        name: pdoc-build
        title: build your python package document with pdoc
        jobs:
          -
            type: component
            kubectl: pdoc-build.yaml
            endpoint: hub.opshub.sh/containerops/pdoc:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/grapy.git entry-mod=grapy"
      -
  -
    type: end
    name: end
    title: End
