apiVersion: v1
kind: Pod
metadata:
 name: pdoc-build
spec:
 containers:
 - name: pdoc
   image: hub.opshub.sh/containerops/pdoc:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/Lupino/grapy.git entry-mod=grapy"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never