uri: containerops/component/python-component-sphinx-build
title: Component for build python document with sphinx
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-sphinx-build
    title: Component, build python document with sphinx
    sequencing: sequence
    actions:
      -
        name: sphinx-build
        title: build your python document with sphinx
        jobs:
          -
            type: component
            kubectl: sphinx-build.yaml
            endpoint: hub.opshub.sh/containerops/sphinx:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/grapy.git entry-path=docs"
      -
  -
    type: end
    name: end
    title: End
