uri: containerops/component/python-component-pylama-test
title: Component for python code analysis with pylama
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-pylama-test
    title: Component, python code analysis with pylama
    sequencing: sequence
    actions:
      -
        name: pylama-test
        title: analysis your python coding style
        jobs:
          -
            type: component
            kubectl: pylama-test.yaml
            endpoint: hub.opshub.sh/containerops/pylama:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/python-aio-periodic.git"
      -
  -
    type: end
    name: end
    title: End
