apiVersion: v1
kind: Pod
metadata:
 name: pylama-test
spec:
 containers:
 - name: pylama
   image: hub.opshub.sh/containerops/pylama:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/Lupino/python-aio-periodic.git"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never
