uri: containerops/component/python-component-pep8-test
title: Component for python code analysis with pep8
version: 1
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: component-pep8-test
    title: Component, python code analysis with pep8
    sequencing: sequence
    actions:
      -
        name: pep8-test
        title: analysis your python coding style
        jobs:
          -
            type: component
            kubectl: pep8-test.yaml
            endpoint: hub.opshub.sh/containerops/pep8:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/python-aio-periodic.git"
      -
  -
    type: end
    name: end
    title: End
