apiVersion: v1
kind: Pod
metadata:
 name: pep8-test
spec:
 containers:
 - name: pep8
   image: hub.opshub.sh/containerops/pep8:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/Lupino/python-aio-periodic.git"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never
