apiVersion: v1
kind: Pod
metadata:
 name: line-profiler-test
spec:
 containers:
 - name: line_profiler
   image: hub.opshub.sh/containerops/line_profiler:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/istrategylabs/python-profiling entry-file=debug.py"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never
